import { 
    EXPO_PUBLIC_ANDROID_VERSION_CODE_ENV, 
    EXPO_PUBLIC_PACKAGE_ENV,
    EXPO_PUBLIC_VERSION_ENV,
    EXPO_PUBLIC_GOOGLEMAPS_APIKEY_ENV,
    EXPO_PUBLIC_CDD_BASE_URL_ENV,
    EXPO_PUBLIC_MIS_BASE_URL_ENV,
    EXPO_PUBLIC_DIAGNOSTIC_MAP_LATITUDE_ENV,
    EXPO_PUBLIC_DIAGNOSTIC_MAP_LONGITUDE_ENV
} from '@env'

const cddBaseURL = process.env.EXPO_PUBLIC_CDD_BASE_URL_ENV ?? EXPO_PUBLIC_CDD_BASE_URL_ENV;
export { cddBaseURL };

const misBaseURL = process.env.EXPO_PUBLIC_MIS_BASE_URL_ENV ?? EXPO_PUBLIC_MIS_BASE_URL_ENV;
export { misBaseURL };

export const DIAGNOSTIC_MAP_LATITUDE = process.env.EXPO_PUBLIC_DIAGNOSTIC_MAP_LATITUDE_ENV ?? EXPO_PUBLIC_DIAGNOSTIC_MAP_LATITUDE_ENV
export const DIAGNOSTIC_MAP_LONGITUDE = process.env.EXPO_PUBLIC_DIAGNOSTIC_MAP_LONGITUDE_ENV ?? EXPO_PUBLIC_DIAGNOSTIC_MAP_LONGITUDE_ENV

export const EXPO_PUBLIC_PACKAGE=process.env.EXPO_PUBLIC_PACKAGE_ENV ?? EXPO_PUBLIC_PACKAGE_ENV
export const EXPO_PUBLIC_ANDROID_VERSION_CODE=process.env.EXPO_PUBLIC_ANDROID_VERSION_CODE_ENV ?? EXPO_PUBLIC_ANDROID_VERSION_CODE_ENV
export const EXPO_PUBLIC_VERSION=process.env.EXPO_PUBLIC_VERSION_ENV ?? EXPO_PUBLIC_VERSION_ENV
export const EXPO_PUBLIC_GOOGLEMAPS_APIKEY=process.env.EXPO_PUBLIC_GOOGLEMAPS_APIKEY_ENV ?? EXPO_PUBLIC_GOOGLEMAPS_APIKEY_ENV